### ISSUE TITLE
custom SSL with rancher

### ISSUE THREAD

**Issue by nitrique** [EugenMayer/docker-image-traefik#1]
Hey Eugen,

I don't understand how to provide a custom SSL for a domain name.

To be clearer here is a schematic : 

traefik + acme -> https on hosta.com, container web in stack A
traefik + comodo -> https on hostb.com, container web in stack B
traefik + acme -> https on hostc.com, container web in stack C

Thanks a lot,
Nicolas

**Comment by EugenMayer** [comment]
As spoken in the chat, Traefik can not do that, only per endpoint https://docs.traefik.io/configuration/entrypoints/#static-certificates - so thats a "cannot do yet"
