### ISSUE TITLE
Acme issue

### ISSUE THREAD

**Issue by nitrique** [EugenMayer/docker-image-traefik#5]
Hi Eugen,

I have an issue related to acme when you move the acme flag from true to false, traefik still ask for cert. Do you already had this kind of issue ?

Thanks,
Nicolas

**Comment by EugenMayer** [comment]
check the generated .toml configuration generated in the container. Check the ACME section and then read the traefik documentation if something is unexpected and provide a bug description if yes.

This image does generate the configuration Traefik needs, so you can always check what is currently available - you find the configuration in the container at ` /etc/traefik/traefik.toml`
