### ISSUE TITLE
TRAEFIK_ADMIN_SSL_CRT_FILE env variable not working

### ISSUE THREAD

**Issue by cloudlady911** [EugenMayer/docker-image-traefik#6]
I am trying to use these Env Variables.
TRAEFIK_ADMIN_SSL_CRT_FILE= /mnt/certs/mydomain.us/fullchain.pem
TRAEFIK_ADMIN_SSL_KEY_FILE= /mnt/certs/mydomain.us/privkey.pem

But this is what gets added to the [entryPoints.traefik] section of the traefik.toml
      [[entryPoints.traefik.tls.certificates]]
      certFile = "/mnt/certs/ssl.crt"
      keyFile = "/mnt/certs/mydomain.us/privkey.pem"

I am using version 1.7 with Rancher 1.6.
TRAEFIK_ADMIN_SSL=true

**Comment by EugenMayer** [comment]
Please read the traefik docs, you are configuring the admin endpoint cert here, not an usual service endpoint

**Comment by cloudlady911** [comment]
I understand that. and I am following the instructions.  What I am saying is that even though I am using the variable correctly, it is not being translated into the .toml file.  I think that is a bug in your container.

**Comment by cloudlady911** [comment]
I found the problem.  You have the env variable listed as TRAEFIK_ADMIN_SSL_CRT_FILE.  But it needs to be TRAEFIK_ADMIN_SSL_CERT_FILE in order to work.
